spring:
  application:
    name=qrfood-backend:
  datasource:
    url: jdbc:mysql://localhost:3306/qrfood
    username: qrfood
    password: HJuy67Qw@HjymPa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
