package az.qrfood.backend.common.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import java.io.Serializable;

/**
 * Base abstract class for all entities in the application.
 * <p>
 * This class provides common properties and mappings for all persistent entities,
 * such as a unique identifier. It is annotated with {@code @MappedSuperclass}
 * so that its fields are inherited by subclasses and mapped to their respective tables.
 * </p>
 */
@MappedSuperclass
@Getter
@Setter
public abstract class BaseEntity implements Serializable {

    /**
     * The unique identifier for the entity.
     * <p>
     * This field is automatically generated by the database using an identity strategy.
     * </p>
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Override
    public String toString() {
        return "{\"BaseEntity\":\n{"
                + "        \"id\":\"" + getId() + "\""
                + "\n}\n}";
    }
}
