### ---------------------- CREATE CATEGORY RANDOM
< scripts/category/create.js
POST {{url}}/api/category/create/eatery/{{eateryId}}
Content-Type: application/json

{
  "nameAz": "{{nameAz}}",
  "nameEn": "{{nameEn}}",
  "nameRu": "{{nameRu}}"
}

### ---------------------- CREATE CATEGORY FOR EARERY
< scripts/category/create.js
POST {{url}}/api/category/create/eatery/23
Content-Type: application/json

{
  "nameAz": "{{nameAz}}",
  "nameEn": "{{nameEn}}",
  "nameRu": "{{nameRu}}"
}

### ---------------------- CREATE CATEGORY FOR EATERY same content
< scripts/category/create.js
POST {{url}}/api/category/create/eatery/22
Content-Type: application/json

{
  "nameAz": "a",
  "nameEn": "b",
  "nameRu": "c"
}

### ---------------------- GET ALL CATEGORIES
GET {{url}}/api/category/categories

### ---------------------- GET CATEGORIES FOR EATERY
GET {{url}}/api/category/categories/by-eatery?eateryId=11

### ---------------------- GET CATEGORIES BY ID
GET {{url}}/api/category?category-id=54



### ---------------------- DELETE CATEGORY
DELETE {{url}}/api/category/15




