

### LOGIN REQUEST
POST http://localhost:8081/api/auth/login
Content-Type: application/json

{
  "email": "nizami.budagov@gmail.com",
  "password": "qqqq1111"
}

> {%
    client.test("Request successful", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.jwt, "JWT token is missing in the response");
        client.global.set("accessToken", response.body.jwt);
        client.log("JWT Token saved: " + response.body.jwt);
    });
%}



### CREATE CATEGORY FOR  SPECIFIED EATERY
//_____________________________________________________________________
@eateryId=/7
< scripts/category/create.js
POST {{url}}{{apiEateries}}{{eateryId}}{{categories1}}
Content-Type: multipart/form-data; boundary=boundary123
Authorization: Bearer {{accessToken}}

--boundary123
Content-Disposition: form-data; name="data"
Content-Type: application/json

{
  "nameAz": "{{nameAz}}",
  "nameEn": "{{nameEn}}",
  "nameRu": "{{nameRu}}"
}

--boundary123
Content-Disposition: form-data; name="image"; filename="soup.webp"
Content-Type: image/webp

< ./image/soup.webp
--boundary123--



### GET ALL CATEGORIES FOR EATERY
//_____________________________________________________________________
@eateryId1 = /7
GET {{url}}{{apiEateries}}{{eateryId1}}{{categories1}}
Authorization: Bearer {{accessToken}}



### GET SPECIFIED BY ID CATEGORY FOR EATERY
//_____________________________________________________________________
@eateryId2 = /6
@categoryId1 = /12
GET {{url}}{{apiEateries}}{{eateryId1}}{{categories1}}{{categoryId1}}
Authorization: Bearer {{accessToken}}



### DELETE CATEGORY
//_____________________________________________________________________
@eateryId3 = /6
@categoryId3 = /12
DELETE {{url}}{{apiEateries}}{{eateryId1}}{{categories1}}{{categoryId1}}
Authorization: Bearer {{accessToken}}


### UPDATE CATEGORY
//_____________________________________________________________________
@eateryId4 = /7
@categoryId4 = /13
PUT {{url}}{{apiEateries}}{{eateryId4}}{{categories1}}{{categoryId4}}
Content-Type: multipart/form-data; boundary=boundary456
Authorization: Bearer {{accessToken}}

--boundary456
Content-Disposition: form-data; name="data"
Content-Type: application/json

{
  "nameAz": "Updated Category Az",
  "nameEn": "Updated Category En",
  "nameRu": "Updated Category Ru"
}

--boundary456
Content-Disposition: form-data; name="image"; filename="updated_soup.webp"
Content-Type: image/webp

< ./image/soup.webp
--boundary456--
