

### CREATE CATEGORY TO EATERY
//_____________________________________________________________________
< scripts/category/create.js
POST {{url}}/api/category/create/eatery/1
Content-Type: application/json

{
  "nameAz": "{{nameAz}}",
  "nameEn": "{{nameEn}}",
  "nameRu": "{{nameRu}}"
}




### GET CATEGORIES FOR EATERY
//_____________________________________________________________________
GET {{url}}/api/category/eatery/1





### ADD CATEGORY TO EATERY same content
//_____________________________________________________________________
< scripts/category/create.js
POST {{url}}/api/category/create/eatery/22
Content-Type: application/json

{
  "nameAz": "a",
  "nameEn": "b",
  "nameRu": "c"
}



### GET ALL CATEGORIES
//_____________________________________________________________________
GET {{url}}/api/category



### GET BY CATEGORY ID
//_____________________________________________________________________
GET {{url}}/api/category/2



### DELETE CATEGORY
//_____________________________________________________________________
DELETE {{url}}/api/category/34





### ADD CATEGORY RANDOM
//_____________________________________________________________________
< scripts/category/create.js
POST {{url}}/api/category/create/eatery/{{eateryId}}
Content-Type: application/json

{
  "nameAz": "{{nameAz}}",
  "nameEn": "{{nameEn}}",
  "nameRu": "{{nameRu}}"
}