



### LOGIN REQUEST
POST {{url}}/api/auth/login
Content-Type: application/json

{
  "email": "nizami.budagov@gmail.com",
  "password": "qqqq1111"
}

> {%
    client.test("Request successful", function() {
        client.assert(response.status === 200, "Response status is not 200");
        client.assert(response.body.jwt, "JWT token is missing in the response");
        client.global.set("accessToken", response.body.jwt);
        client.log("JWT Token saved: " + response.body.jwt);
    });
%}


### CREATE EATERY 1,2,3, ...
//_____________________________________________________________________
< scripts/eatery/create_eatery.js
POST {{url}}{{apiEateries}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "{{name}}",
  "address": "{{address}}",
  "phones": {{phones}},
  "numberOfTables": {{numberOfTables}},
  "geoLat": {{geoLat}},
  "geoLng": {{geoLng}}
}




### GET ALL EATERY
//_____________________________________________________________________
GET {{url}}{{apiEateries}}
Authorization: Bearer {{accessToken}}




### GET BY ID
//_____________________________________________________________________
GET {{url}}{{apiEateries}}/7
Authorization: Bearer {{accessToken}}




### DELETE EATERY
//_____________________________________________________________________
DELETE {{url}}{{apiEateries}}/5
Authorization: Bearer {{accessToken}}




### GET EATERY BY RANDOM ID
//_____________________________________________________________________
< scripts/eatery/findRandom.js
GET {{url}}{{apiEateries}}/{{eateryId}}
Authorization: Bearer {{accessToken}}



