
### CREATE EATERY 1,2,3, ...
//_____________________________________________________________________
< scripts/eatery/create_eatery.js
POST {{url}}/api/eatery
Content-Type: application/json

{
  "name": "{{name}}",
  "address": "{{address}}",
  "phones": {{phones}},
  "categories": {{categories}},
  "tablesAmount": {{tablesAmount}},
  "geoLat": {{geoLat}},
  "geoLng": {{geoLng}}
}




### GET ALL EATERY
//_____________________________________________________________________
GET {{url}}/api/eatery




### GET BY ID
//_____________________________________________________________________
GET {{url}}/api/eatery/1




### DELETE EATERY
//_____________________________________________________________________
DELETE {{url}}/api/eatery/5




### GET EATERY BY RANDOM ID
//_____________________________________________________________________
< scripts/eatery/findRandom.js
GET {{url}}/api/eatery/{{eateryId}}



