

### CREATE NEW MENU FOR CATEGORY(DEFINED)
//_____________________________________________________________________
< scripts/api-menu-create.js
POST {{url}}/api/menu/category-id/3
Content-Type: application/json

{
  "nameAz": "{{nameAz}}",
  "nameEn": "{{nameEn}}",
  "nameRu": "{{nameRu}}",
  "descriptionAz": "{{descriptionAz}}",
  "descriptionEn": "{{descriptionEn}}",
  "descriptionRu": "{{descriptionRu}}",
  "price": {{price}},
  "imageUrl": "https://example.com/images/lentil-soup.jpg",
  "isAvailable": true
}




### GET MENU ITEM BY ID
//_____________________________________________________________________
GET {{url}}/api/menu/1




### GET ALL MENU ITEMS OF A CATEGORY(DEFINED)
//_____________________________________________________________________
GET {{url}}/api/menu/category_id/1




//_____________________________________________________________________
### DELETE MENU ITEM BY ID
DELETE {{url}}/api/menu/menu_id/4




### CREATE MENU FOR CATEGORY(RANDOM)
//_____________________________________________________________________
< scripts/api-menu-create.js

POST {{url}}/api/menu/create/for_category/{{categoryId}}
Content-Type: application/json

{
  "nameAz": "{{nameAz}}",
  "nameEn": "{{nameEn}}",
  "nameRu": "{{nameRu}}",
  "descriptionAz": "{{descriptionAz}}",
  "descriptionEn": "{{descriptionEn}}",
  "descriptionRu": "{{descriptionRu}}",
  "price": "{{price}}",
  "imageUrl": "https://example.com/images/lentil-soup.jpg",
  "isAvailable": true
}


