### ---------------------- CREATE MENU FOR CATEGORY(RANDOM)
< scripts/api-menu-create.js

POST {{url}}/api/menu/create/for_category/{{categoryId}}
Content-Type: application/json

{
  "nameAz": "{{nameAz}}",
  "nameEn": "{{nameEn}}",
  "nameRu": "{{nameRu}}",
  "descriptionAz": "{{descriptionAz}}",
  "descriptionEn": "{{descriptionEn}}",
  "descriptionRu": "{{descriptionRu}}",
  "price": "{{price}}",
  "imageUrl": "https://example.com/images/lentil-soup.jpg",
  "isAvailable": true
}

### ---------------------- ADD MENU TO CATEGORY(DEFINED)
< scripts/api-menu-create.js
POST {{url}}/api/menu/category-id/54
Content-Type: application/json

{
  "nameAz": "{{nameAz}}",
  "nameEn": "{{nameEn}}",
  "nameRu": "{{nameRu}}",
  "descriptionAz": "{{descriptionAz}}",
  "descriptionEn": "{{descriptionEn}}",
  "descriptionRu": "{{descriptionRu}}",
  "price": {{price}},
  "imageUrl": "https://example.com/images/lentil-soup.jpg",
  "isAvailable": true
}

### ---------------------- GET MENU ITEM BY ID
GET {{url}}/api/menu/menu_id/16


### ---------------------- GET ALL MENU ITEMS OF A CATEGORY(DEFINED)
GET {{url}}/api/menu/category_id/54




### ---------------------- DELETE MENU ITEM BY ID
DELETE {{url}}/api/menu/menu_id/4

